// config_catalog_test.go
//
// Tests for the embedded SSSD option catalog and the sssd.conf validation
// built on top of it (unknown parameters, wrong types, bad enum values).
package main

import (
	"strings"
	"testing"
)

// TestEmbeddedCatalogLoads verifies that the catalog generated by
// "-gen-catalog" is really compiled into the binary and contains the options
// the validator relies on.
func TestEmbeddedCatalogLoads(t *testing.T) {
	cat, err := loadEmbeddedCatalog()
	if err != nil {
		t.Fatalf("loadEmbeddedCatalog() error = %v", err)
	}
	if cat == nil {
		t.Fatal("loadEmbeddedCatalog() returned a nil catalog")
	}
	if len(cat.Options) < 100 {
		t.Errorf("catalog contains only %d options, expected the full SSSD set", len(cat.Options))
	}
	if len(cat.OptionNames) != len(cat.Options) {
		t.Errorf("OptionNames (%d) and Options (%d) disagree", len(cat.OptionNames), len(cat.Options))
	}
	for _, want := range []string{"ldap_uri", "id_provider", "debug_level", "ldap_idmap_range_min", "ad_gpo_access_control"} {
		if _, ok := cat.Options[want]; !ok {
			t.Errorf("catalog is missing the well-known option %q", want)
		}
	}
	// The curated enumerations must survive the JSON round-trip.
	if got := cat.Options["ldap_schema"].Values; len(got) == 0 {
		t.Errorf("ldap_schema lost its allowed values")
	}
	if got := cat.Options["ad_gpo_access_control"].Values; len(got) != 3 {
		t.Errorf("ad_gpo_access_control allowed values = %v, want 3 entries", got)
	}
}

func catalogFindings(t *testing.T, body string) *ReportData {
	t.Helper()
	cfg := parseSssdConfig(body)
	report := &ReportData{}
	validateConfigAgainstCatalog(cfg, report)
	return report
}

func hasCategory(r *ReportData, category string) bool {
	for _, f := range r.ConfigFindings {
		if f.Category == category {
			return true
		}
	}
	return false
}

// TestCatalog_UnknownOptionSuggestsTypo covers the classic 'ldap_url' typo.
func TestCatalog_UnknownOptionSuggestsTypo(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nldap_uri = ldap://dc01\nldap_url = ldap://dc02\n")
	if !hasCategory(r, "config_unknown") {
		t.Fatalf("unknown parameter was not reported: %+v", r.ConfigFindings)
	}
	found := false
	for _, f := range r.ConfigFindings {
		if f.Category == "config_unknown" && strings.Contains(f.Message, "ldap_uri") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a 'did you mean ldap_uri?' hint, got %+v", r.ConfigFindings)
	}
	// Typos must never be SevError: SSSD simply ignores the parameter.
	for _, f := range r.ConfigFindings {
		if f.Category == "config_unknown" && f.Severity != SevWarning {
			t.Errorf("unknown-parameter finding severity = %v, want SevWarning", f.Severity)
		}
	}
}

// TestCatalog_KnownOptionsProduceNoFindings guards against false positives on
// a healthy, realistic configuration.
func TestCatalog_KnownOptionsProduceNoFindings(t *testing.T) {
	cfg := "[sssd]\n" +
		"services = nss, pam, ssh\n" +
		"domains = example.com\n" +
		"debug_level = 9\n" +
		"\n[domain/example.com]\n" +
		"id_provider = ad\n" +
		"auth_provider = ad\n" +
		"access_provider = ad\n" +
		"ldap_id_mapping = True\n" +
		"case_sensitive = false\n" +
		"use_fully_qualified_names = False\n" +
		"ldap_uri = ldap://dc01.example.com\n" +
		"timeout = 30\n"
	r := catalogFindings(t, cfg)
	if len(r.ConfigFindings) != 0 {
		t.Errorf("healthy configuration produced catalog findings: %+v", r.ConfigFindings)
	}
}

// TestCatalog_EnumValueRejected checks the enumeration check on a curated
// option value list.
func TestCatalog_EnumValueRejected(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nldap_schema = rfc2309\n")
	if !hasCategory(r, "config_value") {
		t.Fatalf("invalid ldap_schema value was not reported: %+v", r.ConfigFindings)
	}
	for _, f := range r.ConfigFindings {
		if f.Severity != SevWarning {
			t.Errorf("value finding severity = %v, want SevWarning", f.Severity)
		}
	}
	// The documented values must be accepted silently.
	r2 := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nldap_schema = rfc2307bis\n")
	if len(r2.ConfigFindings) != 0 {
		t.Errorf("valid ldap_schema value produced findings: %+v", r2.ConfigFindings)
	}
}

// TestCatalog_BoolTypeMismatch covers the typed-value check.
func TestCatalog_BoolTypeMismatch(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nenumerate = maybe\n")
	if !hasCategory(r, "config_value") {
		t.Fatalf("non-boolean value for 'enumerate' was not reported: %+v", r.ConfigFindings)
	}
	for _, f := range r.ConfigFindings {
		if f.Category == "config_value" && !strings.Contains(f.Message, "boolean") {
			t.Errorf("expected a boolean hint, got %q", f.Message)
		}
	}
}

// TestCatalog_IntTypeMismatch covers the integer check.
func TestCatalog_IntTypeMismatch(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\ndebug_level = verbose\n")
	if !hasCategory(r, "config_value") {
		t.Fatalf("non-integer value for 'debug_level' was not reported: %+v", r.ConfigFindings)
	}
	// Valid spellings must not be flagged.
	for _, ok := range []string{"0", "9", "-1", "+3"} {
		rr := catalogFindings(t, "[domain/example.com]\nid_provider = ad\ndebug_level = "+ok+"\n")
		if len(rr.ConfigFindings) != 0 {
			t.Errorf("debug_level = %s produced findings: %+v", ok, rr.ConfigFindings)
		}
	}
}

// TestInvalidValueReason covers the pure value/type checker directly,
// including the list-OptionMeta paths that the config-level tests cannot reach.
func TestInvalidValueReason(t *testing.T) {
	intOpt := OptionMeta{Name: "timeout", Type: "int"}
	boolOpt := OptionMeta{Name: "enumerate", Type: "bool"}
	listOpt := OptionMeta{Name: "services", Type: "list"}
	enumOpt := OptionMeta{Name: "ldap_schema", Type: "string", Values: []string{"rfc2307", "ad"}}
	listEnum := OptionMeta{Name: "case_sensitive", Type: "list", Values: []string{"true", "false"}}
	strOpt := OptionMeta{Name: "ldap_uri", Type: "string"}

	cases := []struct {
		name string
		opt  OptionMeta
		val  string
		want string // "" means accepted
	}{
		{"empty always accepted", intOpt, "   ", ""},
		{"int ok", intOpt, "30", ""},
		{"int negative ok", intOpt, "-1", ""},
		{"int bad", intOpt, "12x", "integer"},
		{"int sign only", intOpt, "-", "integer"},
		{"bool ok", boolOpt, "TRUE", ""},
		{"bool ok yes", boolOpt, "yes", ""},
		{"bool bad", boolOpt, "maybe", "boolean"},
		{"list of ints accepted", listOpt, "nss, pam, ssh", ""},
		{"enum ok", enumOpt, "ad", ""},
		{"enum bad", enumOpt, "rfc2309", "allowed values"},
		{"list enum uses first token", listEnum, "false, true", ""},
		{"free-form string accepted", strOpt, "ldap://dc01", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := invalidValueReason(tc.opt, tc.val)
			if tc.want == "" {
				if got != "" {
					t.Errorf("invalidValueReason(%v, %q) = %q, want accepted", tc.opt.Type, tc.val, got)
				}
				return
			}
			if !strings.Contains(got, tc.want) {
				t.Errorf("invalidValueReason(%v, %q) = %q, want it to mention %q", tc.opt.Type, tc.val, got, tc.want)
			}
		})
	}
}

// TestIsBoolTokenAndIsIntToken pin the accepted spellings.
func TestIsBoolTokenAndIsIntToken(t *testing.T) {
	for _, v := range []string{"true", "FALSE", "yes", "no", "1", "0", "on", "off", " On "} {
		if !isBoolToken(v) {
			t.Errorf("isBoolToken(%q) = false, want true", v)
		}
	}
	for _, v := range []string{"", "maybe", "2", "tru"} {
		if isBoolToken(v) {
			t.Errorf("isBoolToken(%q) = true, want false", v)
		}
	}
	for _, v := range []string{"0", "42", "-7", "+7", " 15 "} {
		if !isIntToken(v) {
			t.Errorf("isIntToken(%q) = false, want true", v)
		}
	}
	for _, v := range []string{"", "-", "+", "1.5", "0x10", "9a"} {
		if isIntToken(v) {
			t.Errorf("isIntToken(%q) = true, want false", v)
		}
	}
}

// TestLevenshteinAndSuggestions covers the typo-suggestion engine.
func TestLevenshteinAndSuggestions(t *testing.T) {
	if d := levenshtein("kitten", "sitting"); d != 3 {
		t.Errorf("levenshtein(kitten, sitting) = %d, want 3", d)
	}
	if d := levenshtein("", "abc"); d != 3 {
		t.Errorf("levenshtein(\"\", abc) = %d, want 3", d)
	}
	if d := levenshtein("abc", ""); d != 3 {
		t.Errorf("levenshtein(abc, \"\") = %d, want 3", d)
	}
	if d := levenshtein("same", "same"); d != 0 {
		t.Errorf("levenshtein(same, same) = %d, want 0", d)
	}
	if got := abs(-5); got != 5 {
		t.Errorf("abs(-5) = %d, want 5", got)
	}
	if got := abs(5); got != 5 {
		t.Errorf("abs(5) = %d, want 5", got)
	}

	names := []string{"ldap_uri", "ldap_schema", "debug_level", "id_provider"}
	if got := suggestOptionName(names, "ldap_url"); got != "ldap_uri" {
		t.Errorf("suggestOptionName(ldap_url) = %q, want ldap_uri", got)
	}
	if got := suggestOptionName(names, "debg_level"); got != "debug_level" {
		t.Errorf("suggestOptionName(debg_level) = %q, want debug_level", got)
	}
	if got := suggestOptionName(names, "completely_unrelated_setting_name"); got != "" {
		t.Errorf("suggestOptionName(unrelated) = %q, want no suggestion", got)
	}
}

// TestCatalogOptionNamesFallback exercises the branch used when a catalog has
// no pre-computed OptionNames (e.g. a hand-edited catalog.json).
func TestCatalogOptionNamesFallback(t *testing.T) {
	c := &SssdCatalog{Options: map[string]OptionMeta{
		"b_option": {Name: "b_option"},
		"a_option": {Name: "a_option"},
	}}
	got := catalogOptionNames(c)
	if len(got) != 2 || got[0] != "a_option" || got[1] != "b_option" {
		t.Errorf("catalogOptionNames fallback = %v, want sorted [a_option b_option]", got)
	}
	c.OptionNames = []string{"only"}
	if got := catalogOptionNames(c); len(got) != 1 || got[0] != "only" {
		t.Errorf("catalogOptionNames with OptionNames set = %v, want [only]", got)
	}
}
