// config_catalog_test.go
//
// Tests for the embedded SSSD option catalog and the sssd.conf validation
// built on top of it (unknown parameters, wrong types, bad enum values).
package main

import (
	"strings"
	"testing"
)

// TestEmbeddedCatalogLoads verifies that the catalog generated by
// "-gen-catalog" is really compiled into the binary and contains the options
// the validator relies on.
func TestEmbeddedCatalogLoads(t *testing.T) {
	cat, err := loadEmbeddedCatalog()
	if err != nil {
		t.Fatalf("loadEmbeddedCatalog() error = %v", err)
	}
	if cat == nil {
		t.Fatal("loadEmbeddedCatalog() returned a nil catalog")
	}
	if len(cat.Options) < 100 {
		t.Errorf("catalog contains only %d options, expected the full SSSD set", len(cat.Options))
	}
	if len(cat.OptionNames) != len(cat.Options) {
		t.Errorf("OptionNames (%d) and Options (%d) disagree", len(cat.OptionNames), len(cat.Options))
	}
	for _, want := range []string{"ldap_uri", "id_provider", "debug_level", "ldap_idmap_range_min", "ad_gpo_access_control"} {
		if _, ok := cat.Options[want]; !ok {
			t.Errorf("catalog is missing the well-known option %q", want)
		}
	}
	// The curated enumerations must survive the JSON round-trip.
	if got := cat.Options["ldap_schema"].Values; len(got) == 0 {
		t.Errorf("ldap_schema lost its allowed values")
	}
	if got := cat.Options["ad_gpo_access_control"].Values; len(got) != 3 {
		t.Errorf("ad_gpo_access_control allowed values = %v, want 3 entries", got)
	}
}

func catalogFindings(t *testing.T, body string) *ReportData {
	t.Helper()
	cfg := parseSssdConfig(body)
	report := &ReportData{}
	validateConfigAgainstCatalog(cfg, report)
	return report
}

func hasCategory(r *ReportData, category string) bool {
	for _, f := range r.ConfigFindings {
		if f.Category == category {
			return true
		}
	}
	return false
}

// TestCatalog_UnknownOptionSuggestsTypo covers the classic 'ldap_url' typo.
func TestCatalog_UnknownOptionSuggestsTypo(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nldap_uri = ldap://dc01\nldap_url = ldap://dc02\n")
	if !hasCategory(r, "config_unknown") {
		t.Fatalf("unknown parameter was not reported: %+v", r.ConfigFindings)
	}
	found := false
	for _, f := range r.ConfigFindings {
		if f.Category == "config_unknown" && strings.Contains(f.Message, "ldap_uri") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a 'did you mean ldap_uri?' hint, got %+v", r.ConfigFindings)
	}
	// Typos must never be SevError: SSSD simply ignores the parameter.
	for _, f := range r.ConfigFindings {
		if f.Category == "config_unknown" && f.Severity != SevWarning {
			t.Errorf("unknown-parameter finding severity = %v, want SevWarning", f.Severity)
		}
	}
}

// TestCatalog_KnownOptionsProduceNoFindings guards against false positives on
// a healthy, realistic configuration.
func TestCatalog_KnownOptionsProduceNoFindings(t *testing.T) {
	cfg := "[sssd]\n" +
		"services = nss, pam, ssh\n" +
		"domains = example.com\n" +
		"debug_level = 9\n" +
		"\n[domain/example.com]\n" +
		"id_provider = ad\n" +
		"auth_provider = ad\n" +
		"access_provider = ad\n" +
		"ldap_id_mapping = True\n" +
		"case_sensitive = false\n" +
		"use_fully_qualified_names = False\n" +
		"ldap_uri = ldap://dc01.example.com\n" +
		"timeout = 30\n"
	r := catalogFindings(t, cfg)
	if len(r.ConfigFindings) != 0 {
		t.Errorf("healthy configuration produced catalog findings: %+v", r.ConfigFindings)
	}
}

// TestCatalog_EnumValueRejected checks the enumeration check on a curated
// option value list.
func TestCatalog_EnumValueRejected(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nldap_schema = rfc2309\n")
	if !hasCategory(r, "config_value") {
		t.Fatalf("invalid ldap_schema value was not reported: %+v", r.ConfigFindings)
	}
	for _, f := range r.ConfigFindings {
		if f.Severity != SevWarning {
			t.Errorf("value finding severity = %v, want SevWarning", f.Severity)
		}
	}
	// The documented values must be accepted silently.
	r2 := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nldap_schema = rfc2307bis\n")
	if len(r2.ConfigFindings) != 0 {
		t.Errorf("valid ldap_schema value produced findings: %+v", r2.ConfigFindings)
	}
}

// TestCatalog_BoolTypeMismatch covers the typed-value check.
func TestCatalog_BoolTypeMismatch(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nenumerate = maybe\n")
	if !hasCategory(r, "config_value") {
		t.Fatalf("non-boolean value for 'enumerate' was not reported: %+v", r.ConfigFindings)
	}
	for _, f := range r.ConfigFindings {
		if f.Category == "config_value" && !strings.Contains(f.Message, "boolean") {
			t.Errorf("expected a boolean hint, got %q", f.Message)
		}
	}
}

// TestCatalog_IntTypeMismatch covers the integer check.
func TestCatalog_IntTypeMismatch(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\ndebug_level = verbose\n")
	if !hasCategory(r, "config_value") {
		t.Fatalf("non-integer value for 'debug_level' was not reported: %+v", r.ConfigFindings)
	}
	// Valid spellings must not be flagged.
	for _, ok := range []string{"0", "9", "-1", "+3"} {
		rr := catalogFindings(t, "[domain/example.com]\nid_provider = ad\ndebug_level = "+ok+"\n")
		if len(rr.ConfigFindings) != 0 {
			t.Errorf("debug_level = %s produced findings: %+v", ok, rr.ConfigFindings)
		}
	}
}

// TestInvalidValueReason covers the pure value/type checker directly,
// including the list-OptionMeta paths that the config-level tests cannot reach.
func TestInvalidValueReason(t *testing.T) {
	intOpt := OptionMeta{Name: "timeout", Type: "int"}
	boolOpt := OptionMeta{Name: "enumerate", Type: "bool"}
	listOpt := OptionMeta{Name: "services", Type: "list"}
	enumOpt := OptionMeta{Name: "ldap_schema", Type: "string", Values: []string{"rfc2307", "ad"}}
	listEnum := OptionMeta{Name: "case_sensitive", Type: "list", Values: []string{"true", "false"}}
	strOpt := OptionMeta{Name: "ldap_uri", Type: "string"}

	cases := []struct {
		name string
		opt  OptionMeta
		val  string
		want string // "" means accepted
	}{
		{"empty always accepted", intOpt, "   ", ""},
		{"int ok", intOpt, "30", ""},
		{"int negative ok", intOpt, "-1", ""},
		{"int bad", intOpt, "12x", "integer"},
		{"int sign only", intOpt, "-", "integer"},
		{"bool ok", boolOpt, "TRUE", ""},
		{"bool ok yes", boolOpt, "yes", ""},
		{"bool bad", boolOpt, "maybe", "boolean"},
		{"list of ints accepted", listOpt, "nss, pam, ssh", ""},
		{"enum ok", enumOpt, "ad", ""},
		{"enum bad", enumOpt, "rfc2309", "allowed values"},
		{"list enum uses first token", listEnum, "false, true", ""},
		{"free-form string accepted", strOpt, "ldap://dc01", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := invalidValueReason(tc.opt, tc.val)
			if tc.want == "" {
				if got != "" {
					t.Errorf("invalidValueReason(%v, %q) = %q, want accepted", tc.opt.Type, tc.val, got)
				}
				return
			}
			if !strings.Contains(got, tc.want) {
				t.Errorf("invalidValueReason(%v, %q) = %q, want it to mention %q", tc.opt.Type, tc.val, got, tc.want)
			}
		})
	}
}

// TestIsBoolTokenAndIsIntToken pin the accepted spellings.
func TestIsBoolTokenAndIsIntToken(t *testing.T) {
	for _, v := range []string{"true", "FALSE", "yes", "no", "1", "0", "on", "off", " On "} {
		if !isBoolToken(v) {
			t.Errorf("isBoolToken(%q) = false, want true", v)
		}
	}
	for _, v := range []string{"", "maybe", "2", "tru"} {
		if isBoolToken(v) {
			t.Errorf("isBoolToken(%q) = true, want false", v)
		}
	}
	for _, v := range []string{"0", "42", "-7", "+7", " 15 "} {
		if !isIntToken(v) {
			t.Errorf("isIntToken(%q) = false, want true", v)
		}
	}
	for _, v := range []string{"", "-", "+", "1.5", "0x10", "9a"} {
		if isIntToken(v) {
			t.Errorf("isIntToken(%q) = true, want false", v)
		}
	}
}

// TestLevenshteinAndSuggestions covers the typo-suggestion engine.
func TestLevenshteinAndSuggestions(t *testing.T) {
	if d := levenshtein("kitten", "sitting"); d != 3 {
		t.Errorf("levenshtein(kitten, sitting) = %d, want 3", d)
	}
	if d := levenshtein("", "abc"); d != 3 {
		t.Errorf("levenshtein(\"\", abc) = %d, want 3", d)
	}
	if d := levenshtein("abc", ""); d != 3 {
		t.Errorf("levenshtein(abc, \"\") = %d, want 3", d)
	}
	if d := levenshtein("same", "same"); d != 0 {
		t.Errorf("levenshtein(same, same) = %d, want 0", d)
	}
	if got := abs(-5); got != 5 {
		t.Errorf("abs(-5) = %d, want 5", got)
	}
	if got := abs(5); got != 5 {
		t.Errorf("abs(5) = %d, want 5", got)
	}

	names := []string{"ldap_uri", "ldap_schema", "debug_level", "id_provider"}
	if got := suggestOptionName(names, "ldap_url"); got != "ldap_uri" {
		t.Errorf("suggestOptionName(ldap_url) = %q, want ldap_uri", got)
	}
	if got := suggestOptionName(names, "debg_level"); got != "debug_level" {
		t.Errorf("suggestOptionName(debg_level) = %q, want debug_level", got)
	}
	if got := suggestOptionName(names, "completely_unrelated_setting_name"); got != "" {
		t.Errorf("suggestOptionName(unrelated) = %q, want no suggestion", got)
	}
}

// TestCatalogOptionNamesFallback exercises the branch used when a catalog has
// no pre-computed OptionNames (e.g. a hand-edited catalog.json).
func TestCatalogOptionNamesFallback(t *testing.T) {
	c := &SssdCatalog{Options: map[string]OptionMeta{
		"b_option": {Name: "b_option"},
		"a_option": {Name: "a_option"},
	}}
	got := catalogOptionNames(c)
	if len(got) != 2 || got[0] != "a_option" || got[1] != "b_option" {
		t.Errorf("catalogOptionNames fallback = %v, want sorted [a_option b_option]", got)
	}
	c.OptionNames = []string{"only"}
	if got := catalogOptionNames(c); len(got) != 1 || got[0] != "only" {
		t.Errorf("catalogOptionNames with OptionNames set = %v, want [only]", got)
	}
}

// ---------------------------------------------------------------------------
// Regression tests for the false positives found in a real supportconfig
// report. Each case reproduces one of the four findings a user reported.
// ---------------------------------------------------------------------------

// TestCatalog_ConfigFileVersionIsKnown pins the curated option: it is a real,
// documented [sssd] option that is missing from several upstream sssd.conf.5.xml
// releases. Reporting it as "unknown" sends the reader to fix a correct config.
func TestCatalog_ConfigFileVersionIsKnown(t *testing.T) {
	r := catalogFindings(t, "[sssd]\nconfig_file_version = 2\nservices = nss, pam\n")
	for _, f := range r.ConfigFindings {
		if strings.Contains(f.Message, "config_file_version") {
			t.Errorf("config_file_version must not be reported: %s", f.Message)
		}
	}
	cat, err := loadEmbeddedCatalog()
	if err != nil {
		t.Fatalf("embedded catalog: %v", err)
	}
	opt, ok := cat.Options["config_file_version"]
	if !ok {
		t.Fatal("config_file_version is missing from the catalog")
	}
	if opt.Type != "int" {
		t.Errorf("config_file_version type = %q, want int", opt.Type)
	}
	if len(opt.Sections) == 0 || opt.Sections[0] != "sssd" {
		t.Errorf("config_file_version sections = %v, want [sssd]", opt.Sections)
	}
}

// TestCatalog_ReconnectionRetriesIsNotAnOption pins the opposite direction:
// reconnection_retries is not an SSSD option in this release, so it must still
// be reported, and the message must carry its provenance.
func TestCatalog_ReconnectionRetriesIsNotAnOption(t *testing.T) {
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nreconnection_retries = 3\n")
	found := false
	for _, f := range r.ConfigFindings {
		if strings.Contains(f.Message, "reconnection_retries") {
			found = true
			if f.Category != "config_unknown" {
				t.Errorf("reconnection_retries category = %q, want config_unknown", f.Category)
			}
			if !strings.Contains(f.Message, "option catalog") {
				t.Errorf("finding must state its provenance, got: %s", f.Message)
			}
		}
	}
	if !found {
		t.Errorf("reconnection_retries was not reported at all: %+v", r.ConfigFindings)
	}
}

// TestCatalog_EnumerationValuesAreNotOptions is the guard for the extraction bug
// that made "always", "env", "true", "false" and "hybrid" validate as real
// options: they are enumerated VALUES of pam_initgroups_scheme and friends,
// harvested from nested <variablelist> entries in the man page.
func TestCatalog_EnumerationValuesAreNotOptions(t *testing.T) {
	cat, err := loadEmbeddedCatalog()
	if err != nil {
		t.Fatalf("embedded catalog: %v", err)
	}
	for _, junk := range []string{"always", "env", "true", "false", "hybrid", "no_session", "never"} {
		if _, ok := cat.Options[junk]; ok {
			t.Errorf("enumerated value %q leaked into the option list", junk)
		}
	}
	// ...while the real option and its values are both present.
	opt, ok := cat.Options["pam_initgroups_scheme"]
	if !ok {
		t.Fatal("pam_initgroups_scheme is missing from the catalog")
	}
	if !containsFold(opt.Values, "always") {
		t.Errorf("pam_initgroups_scheme values = %v, want the man-page enumeration", opt.Values)
	}
}

// TestCatalog_WrongSectionIsDistinguishedFromTypo covers the case the section
// check exists for: a real option written in a section that never accepts it.
func TestCatalog_WrongSectionIsDistinguishedFromTypo(t *testing.T) {
	// entry_cache_nowait_percentage is an [nss] option; using it under
	// [domain/...] is silently ignored by SSSD but is not a typo.
	r := catalogFindings(t, "[domain/example.com]\nid_provider = ad\nentry_cache_nowait_percentage = 50\n")
	found := false
	for _, f := range r.ConfigFindings {
		if strings.Contains(f.Message, "entry_cache_nowait_percentage") {
			found = true
			if f.Category != "config_section" {
				t.Errorf("category = %q, want config_section", f.Category)
			}
			if !strings.Contains(f.Message, "nss") {
				t.Errorf("message must name the correct section, got: %s", f.Message)
			}
		}
	}
	if !found {
		t.Errorf("option in the wrong section was not reported: %+v", r.ConfigFindings)
	}
}

// TestCatalog_ProviderOptionsValidInDomainSection is the false-positive guard
// for the most common real configuration: AD/LDAP provider options are written
// in [domain/<name>], while the catalog documents them per provider.
func TestCatalog_ProviderOptionsValidInDomainSection(t *testing.T) {
	cfg := "[domain/example.com]\n" +
		"id_provider = ad\n" +
		"ad_domain = example.com\n" +
		"ad_gpo_access_control = permissive\n" +
		"ldap_uri = ldap://dc01.example.com\n" +
		"ldap_id_mapping = True\n" +
		"ldap_schema = ad\n" +
		"access_provider = ad\n"
	r := catalogFindings(t, cfg)
	for _, f := range r.ConfigFindings {
		t.Errorf("valid AD configuration produced a finding [%s]: %s", f.Category, f.Message)
	}
}

// TestCatalog_ProvenanceIsPublished checks that the report always states which
// documentation release its configuration claims are based on, even when no
// finding is raised.
func TestCatalog_ProvenanceIsPublished(t *testing.T) {
	r := catalogFindings(t, "[sssd]\nservices = nss, pam\n")
	if r.CatalogProvenance == "" {
		t.Fatal("report does not publish the catalog provenance")
	}
	for _, want := range []string{"checked against the SSSD", "option catalog", "documentation sources"} {
		if !strings.Contains(r.CatalogProvenance, want) {
			t.Errorf("provenance %q is missing %q", r.CatalogProvenance, want)
		}
	}
}

// TestSectionFamily pins the family extraction used by the section check.
func TestSectionFamily(t *testing.T) {
	cases := map[string]string{
		"domain/example.com": "domain",
		"domain/ad":          "domain",
		"nss":                "nss",
		"":                   "",
		"pam":                "pam",
	}
	for in, want := range cases {
		if got := sectionFamily(in); got != want {
			t.Errorf("sectionFamily(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestWrongSectionReason covers the matching rules directly.
func TestWrongSectionReason(t *testing.T) {
	nssOpt := OptionMeta{Name: "entry_cache_nowait_percentage", Sections: []string{"nss"}}
	adOpt := OptionMeta{Name: "ad_gpo_access_control", Sections: []string{"domain/ad"}}
	anyOpt := OptionMeta{Name: "debug_level", Sections: []string{"*"}}
	noSec := OptionMeta{Name: "orphan", Sections: nil}

	if wrongSectionReason(nssOpt, &SssdSection{Name: "domain/example.com", Kind: "domain"}) == "" {
		t.Error("an [nss] option in [domain/...] must be reported")
	}
	if wrongSectionReason(nssOpt, &SssdSection{Name: "nss", Kind: "nss"}) != "" {
		t.Error("an [nss] option in [nss] must be accepted")
	}
	if wrongSectionReason(adOpt, &SssdSection{Name: "domain/example.com", Kind: "domain"}) != "" {
		t.Error("a provider option in [domain/...] must be accepted")
	}
	if wrongSectionReason(anyOpt, &SssdSection{Name: "pam", Kind: "pam"}) != "" {
		t.Error("the wildcard section must always be accepted")
	}
	if wrongSectionReason(noSec, &SssdSection{Name: "pam", Kind: "pam"}) != "" {
		t.Error("an option without section data must never be reported")
	}
}

// TestIdProviderList pins the source of truth for the accepted id_provider
// values. An earlier version kept a hardcoded literal that drifted from the
// documentation and rejected "files"; both the catalog-derived list and the
// fallback must contain it.
func TestIdProviderList(t *testing.T) {
	allowed, list := idProviderList()
	for _, want := range []string{"ad", "ipa", "ldap", "proxy", "simple", "files"} {
		if !allowed[want] {
			t.Errorf("id_provider %q is not accepted; list = %q", want, list)
		}
	}
	if allowed["nosuchprovider"] {
		t.Error("an unknown id_provider must not be accepted")
	}
	// The fallback used when the catalog is unavailable must agree.
	fallback := map[string]bool{}
	for _, v := range fallbackIdProviders {
		fallback[v] = true
	}
	for _, want := range []string{"ad", "ipa", "ldap", "proxy", "simple", "files"} {
		if !fallback[want] {
			t.Errorf("fallback list is missing %q: %v", want, fallbackIdProviders)
		}
	}
}

// TestNormalizeAPISection pins the mapping from the internal API section names
// to the names that actually appear in sssd.conf.
func TestNormalizeAPISection(t *testing.T) {
	cases := map[string]string{
		"provider":         "domain",
		"provider/ad":      "domain/ad",
		"provider/ad/id":   "domain/ad/id",
		"provider/ldap/id": "domain/ldap/id",
		"domain":           "domain",
		"sssd":             "sssd",
		"pam":              "pam",
	}
	for in, want := range cases {
		if got := normalizeAPISection(in); got != want {
			t.Errorf("normalizeAPISection(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestCatalog_LdapGroupOptionsValidInDomainSection is the regression guard for
// the false positives reported on a real LDAP domain: ldap_group_member,
// ldap_group_name, ldap_group_object_class and ldap_user_member_of are
// declared only by the API definitions, whose "[provider/*/id]" section names
// do not exist in sssd.conf, so they were rejected inside [domain/NAME].
func TestCatalog_LdapGroupOptionsValidInDomainSection(t *testing.T) {
	cat, err := loadEmbeddedCatalog()
	if err != nil {
		t.Fatalf("embedded catalog: %v", err)
	}
	for _, opt := range []string{"ldap_group_member", "ldap_group_name", "ldap_group_object_class", "ldap_user_member_of"} {
		m, ok := cat.Options[opt]
		if !ok {
			t.Errorf("%s is missing from the catalog", opt)
			continue
		}
		if len(m.Sections) == 0 {
			t.Errorf("%s has no section, so it can never validate", opt)
		}
		for _, s := range m.Sections {
			if sectionFamily(s) != "domain" {
				t.Errorf("%s section %q is not in the domain family: %v", opt, s, m.Sections)
			}
		}
	}
	// The end-to-end shape of the reported configuration.
	cfg := "[domain/LDAP]\n" +
		"id_provider = ldap\n" +
		"ldap_uri = ldaps://ldap.example.com:636/\n" +
		"ldap_schema = rfc2307bis\n" +
		"ldap_user_member_of = GroupMembership\n" +
		"ldap_group_search_base = ou=Groups,dc=example,dc=com\n" +
		"ldap_group_object_class = posixGroup\n" +
		"ldap_group_name = cn\n" +
		"ldap_group_member = member\n"
	r := catalogFindings(t, cfg)
	for _, f := range r.ConfigFindings {
		t.Errorf("valid LDAP configuration produced a finding [%s]: %s", f.Category, f.Message)
	}
}

// TestCatalog_IdProviderFilesIsAccepted pins the second false positive from the
// same report: id_provider = files was rejected by a hardcoded literal that had
// drifted from the documentation. The accepted list now comes from the catalog.
func TestCatalog_IdProviderFilesIsAccepted(t *testing.T) {
	parsed := parseSssdConfig("[sssd]\ndomains = files,LDAP\n\n[domain/files]\nid_provider = files\n\n[domain/LDAP]\nid_provider = ldap\n")
	rep := &ReportData{}
	validateDomainStructure(parsed, rep)
	for _, f := range rep.ConfigFindings {
		if strings.Contains(f.Message, "id_provider") {
			t.Errorf("valid id_provider rejected: %s", f.Message)
		}
	}
	// A genuinely invalid provider must still be an error.
	bad := parseSssdConfig("[domain/x]\nid_provider = nosuchprovider\n")
	rep2 := &ReportData{}
	validateDomainStructure(bad, rep2)
	found := false
	for _, f := range rep2.ConfigFindings {
		if strings.Contains(f.Message, "invalid id_provider") {
			found = true
			if f.Severity != SevError {
				t.Errorf("invalid id_provider severity = %v, want SevError", f.Severity)
			}
		}
	}
	if !found {
		t.Error("an invalid id_provider must still be reported as an error")
	}
}

// --- section header validation -------------------------------------------------
//
// The catalog stores man-page section names, not the headers a user writes, so
// these tests pin the two directions that matter: a real domain name must never
// be reported, and a genuinely unknown kind must be.

// A user-named domain is the single most common header in a real sssd.conf. It
// appears in no catalog (the catalog documents domain/ad, domain/ldap, ...), so
// a naive "is this header in the catalog" check would condemn every working
// configuration. This is the regression that test guards.
func TestSectionHeaders_AcceptUserNamedDomain(t *testing.T) {
	cfg := parseSssdConfig("[sssd]\ndebug_level = 0x1F0\n[domain/example.com]\nid_provider = ldap\n")
	report := &ReportData{}
	validateSectionHeaders(cfg, report)

	for _, f := range report.ConfigFindings {
		if f.RuleID == "catalog:unknown-section" {
			t.Errorf("a user-named domain must not be reported: %s", f.Message)
		}
	}
}

func TestSectionHeaders_AcceptsEveryDocumentedKind(t *testing.T) {
	cfg := parseSssdConfig(strings.Join([]string{
		"[sssd]",
		"config_file_version = 2",
		"[nss]",
		"memcache_timeout = 600",
		"[pam]",
		"offline_credentials_expiration = 2",
		"[sudo]",
		"ldap_sudo_smart_refresh = true",
		"[domain/ad]",
		"id_provider = ad",
		"[domain/example.test]",
		"id_provider = ldap",
		"[ifp]",
		"curl_timeout = 10",
		"[autofs]",
		"map-to-user = sssd",
	}, "\n"))
	report := &ReportData{}
	validateSectionHeaders(cfg, report)

	for _, f := range report.ConfigFindings {
		if f.RuleID == "catalog:unknown-section" {
			t.Errorf("documented section kind rejected: %s", f.Message)
		}
	}
}

func TestSectionHeaders_UnknownKindIsReported(t *testing.T) {
	cfg := parseSssdConfig("[sssd]\ndebug_level = 1\n[domian/example.com]\nid_provider = ldap\n")
	report := &ReportData{}
	validateSectionHeaders(cfg, report)

	found := false
	for _, f := range report.ConfigFindings {
		if f.RuleID == "catalog:unknown-section" {
			found = true
			if !strings.Contains(f.Message, "domian/example.com") {
				t.Errorf("finding does not name the offending section: %s", f.Message)
			}
			// A typo gets a correction, not just a rejection.
			if !strings.Contains(f.Message, "Did you mean") {
				t.Errorf("a near-miss section kind should be corrected: %s", f.Message)
			}
			// SSSD ignores the section: the operator has to be told that every
			// option inside it is dead, which is the consequence that matters.
			if !strings.Contains(f.Message, "no effect") {
				t.Errorf("finding should state the consequence: %s", f.Message)
			}
		}
	}
	if !found {
		t.Errorf("expected an unknown-section finding, got %+v", report.ConfigFindings)
	}
}

// The wildcard entry "*" in the catalog means "any section" for option
// placement. Treating it as a section kind would let a bogus header pass.
func TestSectionHeaders_WildcardIsNotASectionKind(t *testing.T) {
	cat, err := loadEmbeddedCatalog()
	if err != nil {
		t.Fatalf("loadEmbeddedCatalog: %v", err)
	}
	if _, ok := knownSectionFamilies(cat)["*"]; ok {
		t.Error(`the catalog wildcard "*" must not be treated as a section kind`)
	}
}

// The verdict has to say which catalog produced it, exactly like every other
// catalog finding, or the operator cannot tell what "documented" means here.
func TestSectionHeaders_CitesCatalogProvenance(t *testing.T) {
	cfg := parseSssdConfig("[bogus]\nfoo = bar\n")
	report := &ReportData{}
	validateSectionHeaders(cfg, report)

	for _, f := range report.ConfigFindings {
		if f.RuleID == "catalog:unknown-section" {
			if !strings.Contains(f.Message, "option catalog") {
				t.Errorf("finding should cite the catalog it checked against: %s", f.Message)
			}
			return
		}
	}
	t.Error("expected an unknown-section finding to check provenance on")
}
