// backend.ts — the single typed façade over the generated Wails bindings.
//
// React components never import ../wailsjs/* directly: every backend call goes
// through this module so that
//   (a) types come from the generated models (frontend/wailsjs/go/models.ts,
//       regenerated by the Wails CLI after any Go signature change), and
//   (b) a UI running outside the Wails window (plain `npm run dev` in a
//       browser) fails with an actionable message instead of a TypeError on
//       the missing window.go bridge.
import {
  Analyze,
  GetCatalogInfo,
  InstallCatalog,
  ListDefinitions,
  OpenCatalogFile,
  OpenDefinitionsRoot,
  OpenFileBrowser,
  ReadRuleYAML,
  SaveJSON,
  SavePDF,
  SaveTXT,
  SaveRuleYAML,
  TestRulesAgainst,
  ValidateRuleYAML,
} from '../../wailsjs/go/main/App';
import { EventsOn, OnFileDrop } from '../../wailsjs/runtime/runtime';
import { main } from '../../wailsjs/go/models';

// ---------------------------------------------------------------------------
// Types: aliases of the generated models, so the UI cannot drift from Go.
// ---------------------------------------------------------------------------
export type ReportData = main.ReportData;
export type ExecutiveSummary = main.ExecutiveSummary;
export type ConfigFinding = main.ConfigFinding;
export type SSSDLogError = main.SSSDLogError;
export type TimelineEvent = main.TimelineEvent;
export type TIDArticle = main.TIDArticle;
export type TemporalCluster = main.TemporalCluster;
export type KBSuggestion = main.KBSuggestion;
export type CorrelationGraph = main.CorrelationGraph;
export type Diagnostic = main.Diagnostic;
export type AnalysisRule = main.AnalysisRule;
export type RuleInfo = main.RuleInfo;
export type RuleValidationResult = main.RuleValidationResult;
export type DefinitionSaveResult = main.DefinitionSaveResult;
export type DefinitionFileInfo = main.DefinitionFileInfo;
export type DefinitionsInventory = main.DefinitionsInventory;
export type RuleDocument = main.RuleDocument;
export type RuleTestOutcome = main.RuleTestOutcome;
export type RuleTestResult = main.RuleTestResult;
export type CatalogInfo = main.CatalogInfo;

/** Definition scopes understood by the Go service (config.User/SystemDefinitionsRoot). */
export const SCOPE_USER = 'user';
export const SCOPE_SYSTEM = 'system';
export type DefinitionScope = typeof SCOPE_USER | typeof SCOPE_SYSTEM;

/** Value the save dialogs return to the frontend when the user cancels. */
export const CANCELLED = 'cancelled';

/** Severity ordinal used by the Go analysis (types.go: SevWarning=0 … SevCritical=2). */
export const SEVERITY_LABELS = ['warning', 'error', 'critical'] as const;

export function severityLabel(severity: number | undefined): string {
  return SEVERITY_LABELS[severity ?? 0] ?? 'warning';
}

// ---------------------------------------------------------------------------
// Availability guard
// ---------------------------------------------------------------------------
interface WailsBridge {
  main?: { App?: Record<string, unknown> };
}

/** True when the React UI runs inside the Wails window (a Go bridge exists). */
export function backendAvailable(): boolean {
  if (typeof window === 'undefined') {
    return false;
  }
  const bridge = (window as unknown as { go?: WailsBridge }).go;
  return Boolean(bridge?.main?.App);
}

function requireBackend(): void {
  if (!backendAvailable()) {
    throw new Error(
      'The sssd-inspector backend is not attached. Start the desktop app (./sssd-inspector) — a plain browser has no Go bridge.',
    );
  }
}

// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------
export async function analyze(path: string, anonymize: boolean): Promise<ReportData> {
  requireBackend();
  return Analyze(path, anonymize);
}

export async function openFileBrowser(): Promise<string> {
  requireBackend();
  return OpenFileBrowser();
}

export async function savePdf(base64Pdf: string): Promise<string> {
  requireBackend();
  return SavePDF(base64Pdf);
}

export async function saveTxt(report: ReportData): Promise<string> {
  requireBackend();
  return SaveTXT(report);
}

export async function saveJson(report: ReportData): Promise<string> {
  requireBackend();
  return SaveJSON(report);
}


// ---------------------------------------------------------------------------
// Definitions Studio (definitions_service.go)
// ---------------------------------------------------------------------------
// Every binding is async, so the "no backend attached" guard always surfaces as
// a rejected promise — never as a synchronous throw from a non-async function.
export async function listDefinitions(): Promise<DefinitionsInventory> {
  requireBackend();
  return ListDefinitions();
}

export async function validateRuleYaml(content: string): Promise<RuleValidationResult> {
  requireBackend();
  return ValidateRuleYAML(content);
}

export async function readRuleYaml(scope: DefinitionScope): Promise<RuleDocument> {
  requireBackend();
  return ReadRuleYAML(scope);
}

export async function saveRuleYaml(content: string, scope: DefinitionScope): Promise<DefinitionSaveResult> {
  requireBackend();
  return SaveRuleYAML(content, scope);
}

export async function testRulesAgainst(targetPath: string): Promise<RuleTestResult> {
  requireBackend();
  return TestRulesAgainst(targetPath);
}

export async function getCatalogInfo(): Promise<CatalogInfo> {
  requireBackend();
  return GetCatalogInfo();
}

/** OS file chooser for a generated catalog.json. */
export async function openCatalogFile(): Promise<string> {
  requireBackend();
  return OpenCatalogFile();
}

/** Installs a generated catalog.json as the override for a scope. */
export async function installCatalog(path: string, scope: DefinitionScope): Promise<DefinitionSaveResult> {
  requireBackend();
  return InstallCatalog(path, scope);
}

export async function openDefinitionsRoot(scope: DefinitionScope): Promise<void> {
  requireBackend();
  return OpenDefinitionsRoot(scope);
}

// ---------------------------------------------------------------------------
// Wails events / drag & drop
// ---------------------------------------------------------------------------
/** Subscribes to the backend progress events; returns an unsubscribe function. */
export function onAnalyzeProgress(cb: (message: string, percentage: number) => void): () => void {
  if (!backendAvailable()) {
    return () => undefined;
  }
  return EventsOn('analyze-progress', cb as (...data: unknown[]) => void);
}

/** Backend warning emitted when definition files were skipped (M0/M1 gate). */
export function onDefinitionsWarning(cb: (diagnostics: Diagnostic[]) => void): () => void {
  if (!backendAvailable()) {
    return () => undefined;
  }
  return EventsOn('definitions-warning', cb as (...data: unknown[]) => void);
}

/** Current drop handler; OnFileDrop itself is registered only once (see below). */
let dropHandler: ((paths: string[]) => void) | null = null;
let dropRegistered = false;

/**
 * Registers the OS drag & drop handler. The Wails runtime has no
 * per-callback unsubscribe (only OnFileDropOff for all), so the native
 * listener is attached once and delegates to the handler passed most
 * recently — which keeps it stable across React re-renders and StrictMode's
 * double effect invocation.
 */
export function onFileDrop(cb: (paths: string[]) => void): boolean {
  dropHandler = cb;
  if (!backendAvailable()) {
    return false;
  }
  if (!dropRegistered) {
    dropRegistered = true;
    OnFileDrop((_x: number, _y: number, paths: string[]) => dropHandler?.(paths), false);
  }
  return true;
}
