// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2) {
  return window['go']['main']['App']['Analyze'](arg1, arg2);
}

export function GetCatalogInfo() {
  return window['go']['main']['App']['GetCatalogInfo']();
}

export function InstallCatalog(arg1, arg2) {
  return window['go']['main']['App']['InstallCatalog'](arg1, arg2);
}

export function ListDefinitions() {
  return window['go']['main']['App']['ListDefinitions']();
}

export function OpenCatalogFile() {
  return window['go']['main']['App']['OpenCatalogFile']();
}

export function OpenDefinitionsRoot(arg1) {
  return window['go']['main']['App']['OpenDefinitionsRoot'](arg1);
}

export function OpenFileBrowser() {
  return window['go']['main']['App']['OpenFileBrowser']();
}

export function ReadRuleYAML(arg1) {
  return window['go']['main']['App']['ReadRuleYAML'](arg1);
}

export function SaveJSON(arg1) {
  return window['go']['main']['App']['SaveJSON'](arg1);
}

export function SavePDF(arg1) {
  return window['go']['main']['App']['SavePDF'](arg1);
}

export function SaveRuleYAML(arg1, arg2) {
  return window['go']['main']['App']['SaveRuleYAML'](arg1, arg2);
}

export function SaveTXT(arg1) {
  return window['go']['main']['App']['SaveTXT'](arg1);
}

export function TestRulesAgainst(arg1) {
  return window['go']['main']['App']['TestRulesAgainst'](arg1);
}

export function ValidateRuleYAML(arg1) {
  return window['go']['main']['App']['ValidateRuleYAML'](arg1);
}
