// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Analyze(arg1:string):Promise<main.ReportData>;

export function OpenFileBrowser():Promise<string>;

export function SaveTXT(arg1:main.ReportData):Promise<string>;
