// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2) {
  return window['go']['main']['App']['Analyze'](arg1, arg2);
}

export function OpenFileBrowser() {
  return window['go']['main']['App']['OpenFileBrowser']();
}

export function SavePDF(arg1) {
  return window['go']['main']['App']['SavePDF'](arg1);
}

export function SaveTXT(arg1) {
  return window['go']['main']['App']['SaveTXT'](arg1);
}
