// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Analyze(arg1:string,arg2:boolean):Promise<types.ReportData>;

export function OpenFileBrowser():Promise<string>;

export function SavePDF(arg1:string):Promise<string>;

export function SaveTXT(arg1:types.ReportData):Promise<string>;
